version: "3"

services:
  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dragon_trainer
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
  telegram-app:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app # Mount your application code into the container
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN_DEV}
      DB_USERNAME: ${DB_USERNAME_DEV}
      DB_PASSWORD: ${DB_PASSWORD_DEV}
      DB_HOST: db
      DB_NAME: dragon_trainer
      DB_PORT: 3306
      ENV: DEV
    networks:
      - backend
    command: sh -c "sleep 9 && python main.py"

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
    name: backend
