name: Build

on:
  push:
    branches:
      - master
      - ay202425

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t mraihandev/dracobot2-telegram-app:latest .

      - name: Push Docker image to Docker Hub
        run: docker push mraihandev/dracobot2-telegram-app:latest
